---
name: Build base OS
on:
  pull_request:
    branches:
      - master
  schedule:
    - cron: '00 14 * * 0'
  push:
    branches:
      - master
    paths-ignore:
      - '**/README.md'
  workflow_dispatch:

env:
  tag: ghcr.io/${{ github.repository.owner }}/$${ git.event.repository.name }}:latest

jobs:
  build_push:
    name: Build and push image
    runs-on: ubuntu-24.04
    permissions:
      packages: write

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build
        run: sudo podman build -t ${{ env.tag }}

      - name: Log into container registry
        run: sudo podman login -u ${{ github.actor }} -p ${{ secrets.GITHUB_TOKEN }} ghcr.io

      - name: Push container
        run: sudo podman push ${{ env.tag }}
